version: '3.8'

services:
  backend-api:
    build: ./backend-api
    ports:
      - "8000:8000"
    volumes:
      - ./backend-api:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - REDIS_HOST=redis
    depends_on:
      - mongo
      - redis

  sandbox-manager:
    build: ./sandbox-manager
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongo-data:
