version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - agent_network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - SANDBOX_URL=http://sandbox:8080
    depends_on:
      - mongo
      - sandbox
    networks:
      - agent_network

  sandbox:
    build: ./sandbox
    ports:
      - "8080:8080"
    networks:
      - agent_network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - agent_network

networks:
  agent_network:
    driver: bridge
